# Generated by Django 5.2.4 on 2025-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_group',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('technician', 'Technician'), ('manager', 'Manager')], max_length=50, null=True),
        ),
    ]
