# Generated by Django 5.2.4 on 2025-07-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='department',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(default='Main Office', max_length=255),
            preserve_default=False,
        ),
    ]
