# Generated by Django 5.2.4 on 2025-07-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_servicerequest_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, to='service.supportdepartment'),
        ),
    ]
