# Generated by Django 5.2.4 on 2025-08-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_servicerequest_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='location',
        ),
    ]
