# Generated by Django 5.2.4 on 2025-08-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_servicerequest_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.location'),
        ),
    ]
