# Generated by Django 5.2.4 on 2025-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_location_servicerequest_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
