# Generated by Django 5.2.4 on 2025-08-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_servicerequest_rejected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supportdepartment',
            name='description',
        ),
    ]
