# Generated by Django 5.2.4 on 2025-08-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_servicecategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Pending Confirmation', 'Pending Confirmation'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='New', max_length=50),
        ),
    ]
