# Generated by Django 5.2.4 on 2025-08-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Awaiting Confirmation', 'Awaiting Confirmation'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
    ]
